language: python
python:
- 2.7
install:
- |
  curl -O \
  https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.17.zip \
  && unzip -q google_appengine_1.9.17.zip
- pip install -r requirements.txt
script: |
  nosetests \
    -v \
    --rednose \
    --with-gae \
    --without-sandbox \
    --gae-lib-root=google_appengine \
    --with-coverage \
    --cover-erase \
    --cover-html \
    --cover-html-dir=htmlcov \
    --cover-package=jetway \
    jetway/
before_install:
  - openssl aes-256-cbc -K $encrypted_1420a752225b_key -iv $encrypted_1420a752225b_iv
    -in testing/keys.zip.enc -out testing/keys.zip -d
  - unzip -f testing/keys.zip && mv service_account_key.json client_secrets.json testing/ 
