language: python
python:
  - 2.7
install:
  - |
      curl -O \
      https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.6.zip \
      && unzip -q google_appengine_1.9.6.zip
  - pip install -r requirements.txt
script: |
    nosetests \
      -v \
      --rednose \
      --with-gae \
      --without-sandbox \
      --gae-lib-root=google_appengine \
      --with-coverage \
      --cover-erase \
      --cover-html \
      --cover-html-dir=htmlcov \
      --cover-package=jetway \
      jetway/
