language: python
python:
- 2.7
before_install:
- openssl aes-256-cbc -K $encrypted_764c4754c84d_key -iv $encrypted_764c4754c84d_iv
  -in testing/service_account_key.json.enc -out config/service_account_key.json -d
#- openssl aes-256-cbc -K $encrypted_764c4754c84d_key -iv $encrypted_764c4754c84d_iv
#  -in testing/client_secrets.json.enc -out config/client_secrets.json -d
install:
- |
  curl -O \
  https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.17.zip \
  && unzip -q google_appengine_1.9.17.zip
- pip install -r requirements.txt
script: |
  nosetests \
    -v \
    --rednose \
    --with-gae \
    --without-sandbox \
    --gae-lib-root=google_appengine \
    --with-coverage \
    --cover-erase \
    --cover-html \
    --cover-html-dir=htmlcov \
    --cover-package=jetway \
    jetway/
