language: python
python:
  - 2.7
script: |
    nosetests \
      -v \
      --rednose \
      --with-gae \
      --without-sandbox \
      --with-coverage \
      --cover-erase \
      --cover-html \
      --cover-html-dir=htmlcov \
      --cover-package=jetway \
      jetway/
