api_version: 1
runtime: python27
threadsafe: true

instance_class: F4_1G

env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'anyvalue'  # https://github.com/shazow/urllib3/issues/618#issuecomment-101795512
  JETWAY_CONFIG: config/jetway.googwebreview.yaml

libraries:
- name: lxml
  version: latest
- name: endpoints
  version: latest
- name: ssl 
  version: latest
- name: pycrypto
  version: latest
- name: jinja2
  version: 2.6
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: yaml
  version: latest

handlers:

- url: /_ah/admin/interactive.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /_ah/spi/.*
  script: app.main.endpoints_app

- url: /_webreview/assets
  static_dir: dist/assets

- url: /.*
  script: app.main.app

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?run_tests.py
- ^.*.example
- ^.*bower_components.*
- ^.*node_modules.*
- ^.*tmp.*
- bower_components
- env
- htmlconv
- lib/Crypto
- lib/PIL
- node_modules
- testing
- webreview-fe
