version: dev
api_version: 1
runtime: python27
threadsafe: true

libraries:
- name: ssl 
  version: latest
- name: pycrypto
  version: latest
- name: jinja2
  version: 2.6
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: yaml
  version: latest

handlers:

- url: /_ah/admin/interactive.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /_jetway/[^/]*/static/css
  static_dir: dist/css

- url: /_jetway/[^/]*/static/js
  static_dir: dist/js

- url: /_jetway/[^/]*/static/html
  static_dir: jetway/frontend/static/html

- url: /_jetway/[^/]*/static/images
  static_dir: jetway/frontend/static/images

- url: /.*
  script: jetway.main.app

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?run_tests.py
- bower_components
- env
- htmlconv
- lib/Crypto
- node_modules
- testing
- ^.*.example
