api_version: 1
runtime: python27
threadsafe: true

env_variables:
  JETWAY_CONFIG: config/jetway.grow-prod.yaml
  GAE_USE_SOCKETS_HTTPLIB: 'anyvalue'  # https://github.com/shazow/urllib3/issues/618#issuecomment-101795512

libraries:
- name: lxml
  version: latest
- name: endpoints
  version: latest
- name: ssl 
  version: latest
- name: pycrypto
  version: latest
- name: jinja2
  version: 2.6
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: yaml
  version: latest

handlers:

- url: /_ah/admin/interactive.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /_ah/spi/.*
  script: jetway.main.endpoints_app

- url: /_app/[^/]*/config/(.*\.(svg|png|gif|jpg))$
  static_files: config/\1
  upload: config/.*\.(svg|png|gif|jpg)$

- url: /_app/[^/]*/static/css
  static_dir: dist/css

- url: /_app/[^/]*/static/js
  static_dir: dist/js

- url: /_app/[^/]*/static/html
  static_dir: jetway/frontend/static/html

- url: /_app/[^/]*/static/images
  static_dir: jetway/frontend/static/images

- url: /.*
  script: jetway.main.app

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?run_tests.py
- bower_components
- env
- htmlconv
- lib/Crypto
- node_modules
- testing
- ^.*.example
